apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    dt.owner: "platform_team"
  name: gitlab
  namespace: argocd
spec:
  sources:
    - repoURL: 'https://github.com/agardnerit/test123.git'
      targetRevision: main
      path: "gitops/manifests/platform/gitlab"
    - repoURL: 'https://charts.gitlab.io'
      targetRevision: 7.5.2
      chart: gitlab
      helm:
        values: |
          gitlab:
            sidekiq:
              replicaCount: 1
              resources:
                requests:
                  cpu: 1m
                  memory: 1M
              annotations:
                metrics.dynatrace.com/scrape: 'true'
                metrics.dynatrace.com/port: '3807'
            webservice:
              replicaCount: 1
              resources:
                requests:
                  cpu: 1m
                  memory: 1M
              annotations:
                metrics.dynatrace.com/scrape: 'true'
                metrics.dynatrace.com/port: '8083'
            gitaly:
              annotations:
                metrics.dynatrace.com/scrape: 'true'
                metrics.dynatrace.com/port: '9236'
            gitlab-exporter:
              annotations:
                metrics.dynatrace.com/scrape: 'true'
                metrics.dynatrace.com/port: '9168'
            kas:
              annotations:
                metrics.dynatrace.com/scrape: 'true'
                metrics.dynatrace.com/port: '8151'
          certmanager:
            install: false
          certmanager-issuer:
              email: "dthotday@example.com"
          upgradeCheck:
            enabled: false
          global:
            edition: ce
            # the "tracing" section is just a guess
            # I do not think it works
            # Apparently gitlab only supports OpenTracing
            # https://docs.gitlab.com/charts/charts/globals.html#tracing
            #tracing:
            #  connection:
            #    string: "http://otel-collector.opentelemetry.svc.cluster.local:4318"
            #    urlTemplate: "https://gitlab.BASE_DOMAIN_PLACEHOLDER/{{ service }}/{{ correlation_id  }}"
            hosts:
              https: false
              domain: BASE_DOMAIN_PLACEHOLDER
              nginx-ingress:
                enabled: false
            ingress:
             class: nginx
             path: /
             configureCertmanager: false
             enabled: false
             tls:
               enabled: false
             annotations:
               nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx-ingress:
            enabled: false
          gitlab-runner:
            install: false
  destination:
    namespace: gitlab
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
