apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    dt.owner: "platform_team"
  name: keptn
  namespace: argocd
spec:
  sources:
    - repoURL: 'https://charts.lifecycle.keptn.sh'
      targetRevision: 0.2.6
      chart: klt
      # helm:
      #   values: |
    - repoURL: 'FORKED_TEMPLATE_REPO_PLACEHOLDER.git'
      targetRevision: main
      path: "FORKED_REPO_GITOPS_CLASSROOMID_PLACEHOLDER/manifests/platform/keptn"
  destination:
    namespace: keptn
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
