---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeaudit
  namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}-cd"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeaudit-namespaces
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeaudit
rules:
  - apiGroups: [""]
    resources:
      - pods
      - podtemplates
      - replicationcontrollers
      - serviceaccounts
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - statefulsets
      - deployments
    verbs: ["list"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
    verbs: ["list"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeaudit-namespaces
subjects:
  - kind: ServiceAccount
    name: kubeaudit
    namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}-cd"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeaudit-namespaces
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeaudit
  namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}-cd"
subjects:
  - kind: ServiceAccount
    name: kubeaudit
    namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}-cd"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeaudit
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubeaudit
  namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}-cd"
spec:
  template:
    spec:
      serviceAccountName: kubeaudit
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kubeaudit
          image: shopify/kubeaudit:v0.11
          args: ["all", "--exitcode", "0", "--namespace", "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}-cd"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
