apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnApp
metadata:
  name: keptndemoapp
  namespace: keptndemo
spec:
  version: "0.0.1"
  revision: 1
  workloads:
  - name: nginx
    version: 0.0.1
#  preDeploymentTasks:
#  - <list of tasks>
#  postDeploymentTasks:
#  - <list of tasks>
#  preDeploymentEvaluations:
#  - <list of evaluations>
#  postDeploymentEvaluations:
#  - <list of evaluations>
