---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-notification-
  namespace: dynatrace
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    dt.owner: "platform_team"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: bizevent-pusher
        image: ghcr.io/dynatrace-oss/bizevent-pusher:v1.1.1
        args: [
          "--tenant",
          "$(TENANT_URL)",
          "--oauth-client-id",
          "$(OAUTH_CLIENT_ID)",
          "--oauth-client-secret",
          "$(OAUTH_CLIENT_SECRET)",
          "--account_urn",
          "$(ACCOUNT_URN)",
          "--payload",
          "{ \"type\": \"sync.finished\", \"app_name\": \"dynatrace\", \"result\": \"success\", \"rev\": 5 }"
        ]
        env:
        - name: TENANT_URL
          valueFrom:
            secretKeyRef:
              name: dt-bizevent-oauth-details
              key: dtTenant
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dt-bizevent-oauth-details
              key: oAuthClientID
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dt-bizevent-oauth-details
              key: oAuthClientSecret
        - name: ACCOUNT_URN
          valueFrom:
            secretKeyRef:
              name: dt-bizevent-oauth-details
              key: accountURN